repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        args: [
          "--py310-plus"
        ]
        language: system
        exclude: |
          (?x)^(
              .*/docker/.*|
              .*/rpc/generatedrpc/.*
          )$
        types:
          - python

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        exclude: |
          (?x)^(
              .*/docker/.*|
              .*/rpc/generatedrpc/.*|
              .*/__init__.py
          )$
        types:
          - python

      - id: black
        name: black
        entry: black
        language: system
        exclude: |
          (?x)^(
              .*/docker/.*|
              .*/rpc/generatedrpc/.*
          )$
        types:
          - python

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        exclude: |
          (?x)^(
              .*/docker/.*|
              .*/rpc/generatedrpc/.*
          )$
        types:
          - python