version: '3.8'

volumes:
  postgres_data: { }

x-app-as-service: &app_as_service
  build: .
  user: "1000"
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  env_file:
    - .env
  depends_on:
    - postgres
  profiles:
    - full_dev

services:
  app:
    <<: *app_as_service
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    profiles:
      - full_dev
      - local_dev

  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    profiles:
      - full_dev
      - local_dev

  celery:
    <<: *app_as_service
    command: /celery_start.sh


