[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = '''
venv
'''

[tool.autoflake]
check = true
in-place = true
remove-unused-variables = true
remove-duplicate-keys = true
remove-all-unused-imports = true