# Generated by Django 4.1.1 on 2022-10-04 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
