# Generated by Django 4.1.3 on 2022-11-04 19:07

import django.db.models.deletion
from django.db import migrations, models

import apps.animals.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="animals.group",
                    ),
                ),
                ("date", models.DateField(blank=True, default=None, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=apps.animals.models.get_icon_path
                    ),
                ),
            ],
        ),
    ]
