# Generated by Django 4.1.1 on 2022-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_squashed_0005_rename_anima_animal_rename_nick_animal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
