# Generated by Django 4.1.1 on 2022-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_alter_animal_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
