# Generated by Django 4.1.1 on 2022-10-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0008_group_animal_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
