name: Main workflow

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      # Need this for any work with repository.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Make autoformatting
        run: |
          black ./
      - name: Check codestyle
        run: |
          flake8 ./